/**
 * generated by Xtext 2.22.0
 */
package org.sodalite.sdl.ansible.ansibleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EAsynchronous Settings</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.EAsynchronousSettings#getAsync <em>Async</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.EAsynchronousSettings#getPoll <em>Poll</em>}</li>
 * </ul>
 *
 * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEAsynchronousSettings()
 * @model
 * @generated
 */
public interface EAsynchronousSettings extends EObject
{
  /**
   * Returns the value of the '<em><b>Async</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Async</em>' containment reference.
   * @see #setAsync(ENumberPassed)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEAsynchronousSettings_Async()
   * @model containment="true"
   * @generated
   */
  ENumberPassed getAsync();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.EAsynchronousSettings#getAsync <em>Async</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Async</em>' containment reference.
   * @see #getAsync()
   * @generated
   */
  void setAsync(ENumberPassed value);

  /**
   * Returns the value of the '<em><b>Poll</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Poll</em>' containment reference.
   * @see #setPoll(ENumberPassed)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEAsynchronousSettings_Poll()
   * @model containment="true"
   * @generated
   */
  ENumberPassed getPoll();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.EAsynchronousSettings#getPoll <em>Poll</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Poll</em>' containment reference.
   * @see #getPoll()
   * @generated
   */
  void setPoll(ENumberPassed value);

} // EAsynchronousSettings
