/**
 * generated by Xtext 2.23.0
 */
package org.sodalite.sdl.ansible.ansibleDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EFunction Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.EFunctionCall#getName <em>Name</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.EFunctionCall#getParameters <em>Parameters</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.EFunctionCall#getEmpty_brackets <em>Empty brackets</em>}</li>
 * </ul>
 *
 * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEFunctionCall()
 * @model
 * @generated
 */
public interface EFunctionCall extends EValuePassedToJinjaExpression
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEFunctionCall_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.EFunctionCall#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Parameters</b></em>' containment reference list.
   * The list contents are of type {@link org.sodalite.sdl.ansible.ansibleDsl.EFilteredExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Parameters</em>' containment reference list.
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEFunctionCall_Parameters()
   * @model containment="true"
   * @generated
   */
  EList<EFilteredExpression> getParameters();

  /**
   * Returns the value of the '<em><b>Empty brackets</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Empty brackets</em>' attribute.
   * @see #setEmpty_brackets(String)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getEFunctionCall_Empty_brackets()
   * @model
   * @generated
   */
  String getEmpty_brackets();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.EFunctionCall#getEmpty_brackets <em>Empty brackets</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Empty brackets</em>' attribute.
   * @see #getEmpty_brackets()
   * @generated
   */
  void setEmpty_brackets(String value);

} // EFunctionCall
