/*
 * generated by Xtext 2.22.0
 */
package org.sodalite.dsl.optimization.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractOptimizationValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.sodalite.dsl.optimization.optimization.OptimizationPackage.eINSTANCE);
		return result;
	}
}
