/*
 * generated by Xtext 2.25.0
 */
package org.sodalite.dsl.ui;

import com.google.inject.Injector;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;
import org.sodalite.dsl.AADM.ui.internal.AADMActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class AADMExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(AADMActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		AADMActivator activator = AADMActivator.getInstance();
		return activator != null ? activator.getInjector(AADMActivator.ORG_SODALITE_DSL_AADM) : null;
	}

}
