/**
 * generated by Xtext 2.19.0
 */
package org.sodalite.dsl.optimization.optimization;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EKeras Case</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.EKerasCase#getKeras <em>Keras</em>}</li>
 * </ul>
 *
 * @see org.sodalite.dsl.optimization.optimization.OptimizationPackage#getEKerasCase()
 * @model
 * @generated
 */
public interface EKerasCase extends EAITrainingCases
{
  /**
   * Returns the value of the '<em><b>Keras</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Keras</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keras</em>' containment reference.
   * @see #setKeras(EKeras)
   * @see org.sodalite.dsl.optimization.optimization.OptimizationPackage#getEKerasCase_Keras()
   * @model containment="true"
   * @generated
   */
  EKeras getKeras();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.optimization.optimization.EKerasCase#getKeras <em>Keras</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Keras</em>' containment reference.
   * @see #getKeras()
   * @generated
   */
  void setKeras(EKeras value);

} // EKerasCase
