/**
 * generated by Xtext 2.23.0
 */
package org.sodalite.sdl.ansible.ansibleDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ELoop Control</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getLabel <em>Label</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getPause <em>Pause</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getIndex_var <em>Index var</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getLoop_var <em>Loop var</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getExtended <em>Extended</em>}</li>
 * </ul>
 *
 * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getELoopControl()
 * @model
 * @generated
 */
public interface ELoopControl extends EObject
{
  /**
   * Returns the value of the '<em><b>Label</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Label</em>' containment reference.
   * @see #setLabel(EValuePassed)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getELoopControl_Label()
   * @model containment="true"
   * @generated
   */
  EValuePassed getLabel();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getLabel <em>Label</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Label</em>' containment reference.
   * @see #getLabel()
   * @generated
   */
  void setLabel(EValuePassed value);

  /**
   * Returns the value of the '<em><b>Pause</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Pause</em>' attribute.
   * @see #setPause(int)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getELoopControl_Pause()
   * @model
   * @generated
   */
  int getPause();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getPause <em>Pause</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Pause</em>' attribute.
   * @see #getPause()
   * @generated
   */
  void setPause(int value);

  /**
   * Returns the value of the '<em><b>Index var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Index var</em>' attribute.
   * @see #setIndex_var(String)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getELoopControl_Index_var()
   * @model
   * @generated
   */
  String getIndex_var();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getIndex_var <em>Index var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Index var</em>' attribute.
   * @see #getIndex_var()
   * @generated
   */
  void setIndex_var(String value);

  /**
   * Returns the value of the '<em><b>Loop var</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Loop var</em>' attribute.
   * @see #setLoop_var(String)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getELoopControl_Loop_var()
   * @model
   * @generated
   */
  String getLoop_var();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getLoop_var <em>Loop var</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Loop var</em>' attribute.
   * @see #getLoop_var()
   * @generated
   */
  void setLoop_var(String value);

  /**
   * Returns the value of the '<em><b>Extended</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Extended</em>' attribute.
   * @see #setExtended(String)
   * @see org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage#getELoopControl_Extended()
   * @model
   * @generated
   */
  String getExtended();

  /**
   * Sets the value of the '{@link org.sodalite.sdl.ansible.ansibleDsl.ELoopControl#getExtended <em>Extended</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Extended</em>' attribute.
   * @see #getExtended()
   * @generated
   */
  void setExtended(String value);

} // ELoopControl
