/**
 * generated by Xtext 2.23.0
 */
package org.sodalite.sdl.ansible.ansibleDsl.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage;
import org.sodalite.sdl.ansible.ansibleDsl.EDeclaredVariableReferenceOrString;
import org.sodalite.sdl.ansible.ansibleDsl.EFilteredVariable;
import org.sodalite.sdl.ansible.ansibleDsl.EFilteredVariableOrString;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EFiltered Variable</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.impl.EFilteredVariableImpl#getString <em>String</em>}</li>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.impl.EFilteredVariableImpl#getVariable_reference_or_string <em>Variable reference or string</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EFilteredVariableImpl extends ELoopListImpl implements EFilteredVariable
{
  /**
   * The default value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected static final String STRING_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getString() <em>String</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getString()
   * @generated
   * @ordered
   */
  protected String string = STRING_EDEFAULT;

  /**
   * The cached value of the '{@link #getVariable_reference_or_string() <em>Variable reference or string</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getVariable_reference_or_string()
   * @generated
   * @ordered
   */
  protected EList<EDeclaredVariableReferenceOrString> variable_reference_or_string;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EFilteredVariableImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsibleDslPackage.Literals.EFILTERED_VARIABLE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getString()
  {
    return string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setString(String newString)
  {
    String oldString = string;
    string = newString;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsibleDslPackage.EFILTERED_VARIABLE__STRING, oldString, string));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<EDeclaredVariableReferenceOrString> getVariable_reference_or_string()
  {
    if (variable_reference_or_string == null)
    {
      variable_reference_or_string = new EObjectContainmentEList<EDeclaredVariableReferenceOrString>(EDeclaredVariableReferenceOrString.class, this, AnsibleDslPackage.EFILTERED_VARIABLE__VARIABLE_REFERENCE_OR_STRING);
    }
    return variable_reference_or_string;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.EFILTERED_VARIABLE__VARIABLE_REFERENCE_OR_STRING:
        return ((InternalEList<?>)getVariable_reference_or_string()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.EFILTERED_VARIABLE__STRING:
        return getString();
      case AnsibleDslPackage.EFILTERED_VARIABLE__VARIABLE_REFERENCE_OR_STRING:
        return getVariable_reference_or_string();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.EFILTERED_VARIABLE__STRING:
        setString((String)newValue);
        return;
      case AnsibleDslPackage.EFILTERED_VARIABLE__VARIABLE_REFERENCE_OR_STRING:
        getVariable_reference_or_string().clear();
        getVariable_reference_or_string().addAll((Collection<? extends EDeclaredVariableReferenceOrString>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.EFILTERED_VARIABLE__STRING:
        setString(STRING_EDEFAULT);
        return;
      case AnsibleDslPackage.EFILTERED_VARIABLE__VARIABLE_REFERENCE_OR_STRING:
        getVariable_reference_or_string().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.EFILTERED_VARIABLE__STRING:
        return STRING_EDEFAULT == null ? string != null : !STRING_EDEFAULT.equals(string);
      case AnsibleDslPackage.EFILTERED_VARIABLE__VARIABLE_REFERENCE_OR_STRING:
        return variable_reference_or_string != null && !variable_reference_or_string.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eBaseStructuralFeatureID(int derivedFeatureID, Class<?> baseClass)
  {
    if (baseClass == EFilteredVariableOrString.class)
    {
      switch (derivedFeatureID)
      {
        case AnsibleDslPackage.EFILTERED_VARIABLE__STRING: return AnsibleDslPackage.EFILTERED_VARIABLE_OR_STRING__STRING;
        default: return -1;
      }
    }
    return super.eBaseStructuralFeatureID(derivedFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public int eDerivedStructuralFeatureID(int baseFeatureID, Class<?> baseClass)
  {
    if (baseClass == EFilteredVariableOrString.class)
    {
      switch (baseFeatureID)
      {
        case AnsibleDslPackage.EFILTERED_VARIABLE_OR_STRING__STRING: return AnsibleDslPackage.EFILTERED_VARIABLE__STRING;
        default: return -1;
      }
    }
    return super.eDerivedStructuralFeatureID(baseFeatureID, baseClass);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (string: ");
    result.append(string);
    result.append(')');
    return result.toString();
  }

} //EFilteredVariableImpl
