package org.sodalite.dsl.ui.contentassist;

import java.util.Map;
import java.util.stream.Collectors;
import java.util.stream.Stream;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.Keyword;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.impl.KeywordImpl;

public class AlertingProposalHelper {
	static Map<String, String> proposals = null;
	static {
		proposals = Stream.of(new String[][] { { "slurm_job_state",
				"slurm_job_state{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_walltime_used",
						"slurm_job_walltime_used{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_cpu_n",
						"slurm_job_cpu_n{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_memory_virtual_max",
						"slurm_job_memory_virtual_max{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_memory_physical_max",
						"slurm_job_memory_physical_max{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_queued",
						"slurm_job_queued{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_exit_code",
						"slurm_job_exit_code{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_job_exit_signal",
						"slurm_job_exit_signal{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_partition}" },
				{ "slurm_partition_availability",
						"slurm_partition_availability{monitoring_id, deployment_label, hpc, partition}" },
				{ "slurm_partition_cores_idle",
						"slurm_partition_cores_idle{monitoring_id, deployment_label, hpc, partition}" },
				{ "slurm_partition_cores_allocated",
						"slurm_partition_cores_allocated{monitoring_id, deployment_label, hpc, partition}" },
				{ "slurm_partition_cores_total",
						"slurm_partition_cores_total{monitoring_id, deployment_label, hpc, partition}" },
				// PBS Exporter
				{ "pbs_job_state",
						"pbs_job_state{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_priority",
						"pbs_job_priority{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_walltime_used",
						"pbs_job_walltime_used{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_walltime_max",
						"pbs_job_walltime_max{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_walltime_remaining",
						"pbs_job_walltime_remaining{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_cpu_time",
						"pbs_job_cpu_time{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_cpu_n",
						"pbs_job_cpu_n{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_mem_virtual",
						"pbs_job_mem_virtual{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_mem_physical",
						"pbs_job_mem_physical{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_time_queued",
						"pbs_job_time_queued{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_job_exit_status",
						"pbs_job_exit_status{monitoring_id, deployment_label, hpc, job_id, job_name, job_user, job_queue}" },
				{ "pbs_queue_enabled",
						"pbs_queue_enabled{monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_started",
						"pbs_queue_started{monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_total",
						"pbs_queue_jobs_total {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_max",
						"pbs_queue_jobs_max {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_queued",
						"pbs_queue_jobs_queued {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_running",
						"pbs_queue_jobs_running {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_held",
						"pbs_queue_jobs_held {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_waiting",
						"pbs_queue_jobs_waiting {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_transit",
						"pbs_queue_jobs_transit {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_exiting",
						"pbs_queue_jobs_exiting {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				{ "pbs_queue_jobs_complete",
						"pbs_queue_jobs_complete {monitoring_id, deployment_label, hpc, queue_name, queue_type}" },
				// Node Exporter
				{ "node_arp_entries", "node_arp_entries{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_boot_time_seconds", "node_boot_time_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_context_switches_total",
						"node_context_switches_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_cooling_device_cur_state",
						"node_cooling_device_cur_state{deployment_label, instance_name, monitoring_id, name, type}" },
				{ "node_cpu_guest_seconds_total",
						"node_cpu_guest_seconds_total{cpu, deployment_label, instance_name, mode, monitoring_id}" },
				{ "node_cpu_seconds_total",
						"node_cpu_seconds_total{cpu, deployment_label, instance_name, mode, monitoring_id}" },
				{ "node_disk_io_now", "node_disk_io_now{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_io_time_seconds_total",
						"node_disk_io_time_seconds_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_io_time_weighted_seconds_total",
						"node_disk_io_time_weighted_seconds_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_read_bytes_total",
						"node_disk_read_bytes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_read_time_seconds_total",
						"node_disk_read_time_seconds_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_reads_completed_total",
						"node_disk_reads_completed_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_reads_merged_total",
						"node_disk_reads_merged_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_write_time_seconds_total",
						"node_disk_write_time_seconds_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_writes_completed_total",
						"node_disk_writes_completed_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_writes_merged_total",
						"node_disk_writes_merged_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_disk_written_bytes_total",
						"node_disk_written_bytes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_entropy_available_bits",
						"node_entropy_available_bits{deployment_label, instance_name, monitoring_id}" },
				{ "node_entropy_pool_size_bits",
						"node_entropy_pool_size_bits{deployment_label, instance_name, monitoring_id}" },
				{ "node_exporter_build_info", "node_exporter_build_info{branch, goversion, revision, version}" },
				{ "node_filefd_allocated", "node_filefd_allocated{deployment_label, instance_name, monitoring_id}" },
				{ "node_filefd_maximum", "node_filefd_maximum{deployment_label, instance_name, monitoring_id}" },
				{ "node_filesystem_avail_bytes",
						"node_filesystem_avail_bytes{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_filesystem_device_error",
						"node_filesystem_device_error{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_filesystem_files",
						"node_filesystem_files{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_filesystem_files_free",
						"node_filesystem_files_free{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_filesystem_free_bytes",
						"node_filesystem_free_bytes{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_filesystem_readonly",
						"node_filesystem_readonly{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_filesystem_size_bytes",
						"node_filesystem_size_bytes{device, fstype, deployment_label, instance_name, monitoring_id, mountpoint}" },
				{ "node_forks_total", "node_forks_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_intr_total", "node_intr_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_load1", "node_load1{deployment_label, instance_name, monitoring_id}" },
				{ "node_load15", "node_load15{deployment_label, instance_name, monitoring_id}" },
				{ "node_load5", "node_load5{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Active_anon_bytes",
						"node_memory_Active_anon_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Active_bytes",
						"node_memory_Active_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Active_file_bytes",
						"node_memory_Active_file_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_AnonHugePages_bytes",
						"node_memory_AnonHugePages_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_AnonPages_bytes",
						"node_memory_AnonPages_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Bounce_bytes",
						"node_memory_Bounce_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Buffers_bytes",
						"node_memory_Buffers_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Cached_bytes",
						"node_memory_Cached_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_CmaFree_bytes",
						"node_memory_CmaFree_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_CmaTotal_bytes",
						"node_memory_CmaTotal_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_CommitLimit_bytes",
						"node_memory_CommitLimit_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Committed_AS_bytes",
						"node_memory_Committed_AS_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_DirectMap1G_bytes",
						"node_memory_DirectMap1G_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_DirectMap2M_bytes",
						"node_memory_DirectMap2M_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_DirectMap4k_bytes",
						"node_memory_DirectMap4k_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Dirty_bytes",
						"node_memory_Dirty_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_HardwareCorrupted_bytes",
						"node_memory_HardwareCorrupted_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_HugePages_Free",
						"node_memory_HugePages_Free{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_HugePages_Rsvd",
						"node_memory_HugePages_Rsvd{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_HugePages_Surp",
						"node_memory_HugePages_Surp{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_HugePages_Total",
						"node_memory_HugePages_Total{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Hugepagesize_bytes",
						"node_memory_Hugepagesize_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Inactive_anon_bytes",
						"node_memory_Inactive_anon_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "", "node_memory_Inactive_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Inactive_bytes",
						"node_memory_Inactive_file_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_KernelStack_bytes",
						"node_memory_KernelStack_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Mapped_bytes",
						"node_memory_Mapped_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_MemAvailable_bytes",
						"node_memory_MemAvailable_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_MemFree_bytes",
						"node_memory_MemFree_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_MemTotal_bytes",
						"node_memory_MemTotal_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Mlocked_bytes",
						"node_memory_Mlocked_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_NFS_Unstable_bytes",
						"node_memory_NFS_Unstable_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_PageTables_bytes",
						"node_memory_PageTables_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_SReclaimable_bytes",
						"node_memory_SReclaimable_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_SUnreclaim_bytes",
						"node_memory_SUnreclaim_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_ShmemHugePages_bytes",
						"node_memory_ShmemHugePages_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_ShmemPmdMapped_bytes",
						"node_memory_ShmemPmdMapped_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Shmem_bytes",
						"node_memory_Shmem_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Slab_bytes", "node_memory_Slab_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_SwapCached_bytes",
						"node_memory_SwapCached_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_SwapFree_bytes",
						"node_memory_SwapFree_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_SwapTotal_bytes",
						"node_memory_SwapTotal_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Unevictable_bytes",
						"node_memory_Unevictable_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_VmallocChunk_bytes",
						"node_memory_VmallocChunk_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_VmallocTotal_bytes",
						"node_memory_VmallocTotal_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_VmallocUsed_bytes",
						"node_memory_VmallocUsed_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_WritebackTmp_bytes",
						"node_memory_WritebackTmp_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_memory_Writeback_bytes",
						"node_memory_Writeback_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Icmp6_InErrors",
						"node_netstat_Icmp6_InErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Icmp6_InMsgs",
						"node_netstat_Icmp6_InMsgs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Icmp6_OutMsgs",
						"node_netstat_Icmp6_OutMsgs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Icmp_InErrors",
						"node_netstat_Icmp_InErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Icmp_InMsgs",
						"node_netstat_Icmp_InMsgs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Icmp_OutMsgs",
						"node_netstat_Icmp_OutMsgs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Ip6_InOctets",
						"node_netstat_Ip6_InOctets{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Ip6_OutOctets",
						"node_netstat_Ip6_OutOctets{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_IpExt_InOctets",
						"node_netstat_IpExt_InOctets{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_IpExt_OutOctets",
						"node_netstat_IpExt_OutOctets{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Ip_Forwarding",
						"node_netstat_Ip_Forwarding{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_TcpExt_ListenDrops",
						"node_netstat_TcpExt_ListenDrops{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_TcpExt_ListenOverflows",
						"node_netstat_TcpExt_ListenOverflows{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_TcpExt_SyncookiesFailed",
						"node_netstat_TcpExt_SyncookiesFailed{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_TcpExt_SyncookiesRecv",
						"node_netstat_TcpExt_SyncookiesRecv{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_TcpExt_SyncookiesSent",
						"node_netstat_TcpExt_SyncookiesSent{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_TcpExt_TCPSynRetrans",
						"node_netstat_TcpExt_TCPSynRetrans{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_ActiveOpens",
						"node_netstat_Tcp_ActiveOpens{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_CurrEstab",
						"node_netstat_Tcp_CurrEstab{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_InErrs",
						"node_netstat_Tcp_InErrs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_InSegs",
						"node_netstat_Tcp_InSegs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_OutRsts",
						"node_netstat_Tcp_OutRsts{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_OutSegs",
						"node_netstat_Tcp_OutSegs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_PassiveOpens",
						"node_netstat_Tcp_PassiveOpens{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Tcp_RetransSegs",
						"node_netstat_Tcp_RetransSegs{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp6_InDatagrams",
						"node_netstat_Udp6_InDatagrams{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp6_InErrors",
						"node_netstat_Udp6_InErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp6_NoPorts",
						"node_netstat_Udp6_NoPorts{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp6_OutDatagrams",
						"node_netstat_Udp6_OutDatagrams{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp6_RcvbufErrors",
						"node_netstat_Udp6_RcvbufErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp6_SndbufErrors",
						"node_netstat_Udp6_SndbufErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_UdpLite6_InErrors",
						"node_netstat_UdpLite6_InErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_UdpLite_InErrors",
						"node_netstat_UdpLite_InErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp_InDatagrams",
						"node_netstat_Udp_InDatagrams{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp_InErrors",
						"node_netstat_Udp_InErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp_NoPorts",
						"node_netstat_Udp_NoPorts{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp_OutDatagrams",
						"node_netstat_Udp_OutDatagrams{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp_RcvbufErrors",
						"node_netstat_Udp_RcvbufErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_netstat_Udp_SndbufErrors",
						"node_netstat_Udp_SndbufErrors{deployment_label, instance_name, monitoring_id}" },
				{ "node_network_address_assign_type",
						"node_network_address_assign_type{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_carrier_changes_total",
						"node_network_carrier_changes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_carrier_down_changes_total",
						"node_network_carrier_down_changes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_carrier_up_changes_total",
						"node_network_carrier_up_changes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_device_id",
						"node_network_device_id{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_dormant",
						"node_network_dormant{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_flags", "node_network_flags{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_iface_id",
						"node_network_iface_id{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_iface_link",
						"node_network_iface_link{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_iface_link_mode",
						"node_network_iface_link_mode{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_info",
						"node_network_info{address, broadcast, device, duplex, deployment_label, ifalias, instance_name, monitoring_id, operstate}" },
				{ "node_network_mtu_bytes",
						"node_network_mtu_bytes{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_name_assign_type",
						"node_network_name_assign_type{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_net_dev_group",
						"node_network_net_dev_group{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_protocol_type",
						"node_network_protocol_type{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_bytes_total",
						"node_network_receive_bytes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_compressed_total",
						"node_network_receive_compressed_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_drop_total",
						"node_network_receive_drop_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_errs_total",
						"node_network_receive_errs_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_fifo_total",
						"node_network_receive_fifo_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_frame_total",
						"node_network_receive_frame_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_multicast_total",
						"node_network_receive_multicast_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_receive_packets_total",
						"node_network_receive_packets_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_speed_bytes",
						"node_network_speed_bytes{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_bytes_total",
						"node_network_transmit_bytes_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_carrier_total",
						"node_network_transmit_carrier_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_colls_total",
						"node_network_transmit_colls_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_compressed_total",
						"node_network_transmit_compressed_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_drop_total",
						"node_network_transmit_drop_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_errs_total",
						"node_network_transmit_errs_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_fifo_total",
						"node_network_transmit_fifo_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_packets_total",
						"node_network_transmit_packets_total{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_transmit_queue_length",
						"node_network_transmit_queue_length{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_network_up", "node_network_up{device, deployment_label, instance_name, monitoring_id}" },
				{ "node_nf_conntrack_entries",
						"node_nf_conntrack_entries{deployment_label, instance_name, monitoring_id}" },
				{ "node_nf_conntrack_entries_limit",
						"node_nf_conntrack_entries_limit{deployment_label, instance_name, monitoring_id}" },
				{ "node_procs_blocked", "node_procs_blocked{deployment_label, instance_name, monitoring_id}" },
				{ "node_procs_running", "node_procs_running{deployment_label, instance_name, monitoring_id}" },
				{ "node_schedstat_running_seconds_total",
						"node_schedstat_running_seconds_total{cpu, deployment_label, instance_name, monitoring_id}" },
				{ "node_schedstat_timeslices_total",
						"node_schedstat_timeslices_total{cpu, deployment_label, instance_name, monitoring_id}" },
				{ "node_schedstat_waiting_seconds_total",
						"node_schedstat_waiting_seconds_total{cpu, deployment_label, instance_name, monitoring_id}" },
				{ "node_scrape_collector_duration_seconds",
						"node_scrape_collector_duration_seconds{collector, deployment_label, instance_name, monitoring_id}" },
				{ "node_scrape_collector_success",
						"node_scrape_collector_success{collector, deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_FRAG6_inuse",
						"node_sockstat_FRAG6_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_FRAG6_memory",
						"node_sockstat_FRAG6_memory{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_FRAG_inuse",
						"node_sockstat_FRAG_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_FRAG_memory",
						"node_sockstat_FRAG_memory{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_RAW6_inuse",
						"node_sockstat_RAW6_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_RAW_inuse",
						"node_sockstat_RAW_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP6_inuse",
						"node_sockstat_TCP6_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP_alloc",
						"node_sockstat_TCP_alloc{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP_inuse",
						"node_sockstat_TCP_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP_mem", "node_sockstat_TCP_mem{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP_mem_bytes",
						"node_sockstat_TCP_mem_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP_orphan",
						"node_sockstat_TCP_orphan{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_TCP_tw", "node_sockstat_TCP_tw{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_UDP6_inuse",
						"node_sockstat_UDP6_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_UDPLITE6_inuse",
						"node_sockstat_UDPLITE6_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_UDPLITE_inuse",
						"node_sockstat_UDPLITE_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_UDP_inuse",
						"node_sockstat_UDP_inuse{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_UDP_mem", "node_sockstat_UDP_mem{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_UDP_mem_bytes",
						"node_sockstat_UDP_mem_bytes{deployment_label, instance_name, monitoring_id}" },
				{ "node_sockstat_sockets_used",
						"node_sockstat_sockets_used{deployment_label, instance_name, monitoring_id}" },
				{ "node_softnet_dropped_total",
						"node_softnet_dropped_total{cpu, deployment_label, instance_name, monitoring_id}" },
				{ "node_softnet_processed_total",
						"node_softnet_processed_total{cpu, deployment_label, instance_name, monitoring_id}" },
				{ "node_softnet_times_squeezed_total",
						"node_softnet_times_squeezed_total{cpu, deployment_label, instance_name, monitoring_id}" },
				{ "node_textfile_scrape_error",
						"node_textfile_scrape_error{deployment_label, instance_name, monitoring_id}" },
				{ "node_time_seconds", "node_time_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_estimated_error_seconds",
						"node_timex_estimated_error_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_frequency_adjustment_ratio",
						"node_timex_frequency_adjustment_ratio{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_loop_time_constant",
						"node_timex_loop_time_constant{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_maxerror_seconds",
						"node_timex_maxerror_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_offset_seconds",
						"node_timex_offset_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_calibration_total",
						"node_timex_pps_calibration_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_error_total",
						"node_timex_pps_error_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_frequency_hertz",
						"node_timex_pps_frequency_hertz{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_jitter_seconds",
						"node_timex_pps_jitter_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_jitter_total",
						"node_timex_pps_jitter_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_shift_seconds",
						"node_timex_pps_shift_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_stability_exceeded_total",
						"node_timex_pps_stability_exceeded_total{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_pps_stability_hertz",
						"node_timex_pps_stability_hertz{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_status", "node_timex_status{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_sync_status", "node_timex_sync_status{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_tai_offset_seconds",
						"node_timex_tai_offset_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_timex_tick_seconds",
						"node_timex_tick_seconds{deployment_label, instance_name, monitoring_id}" },
				{ "node_udp_queues", "node_udp_queues{deployment_label, instance_name, ip, monitoring_id, queue}" },
				{ "node_uname_info", "node_uname_info{domainname, machine, nodename, release, sysname, version}" },
				{ "node_vmstat_oom_kill", "node_vmstat_oom_kill{deployment_label, instance_name, monitoring_id}" },
				{ "node_vmstat_pgfault", "node_vmstat_pgfault{deployment_label, instance_name, monitoring_id}" },
				{ "node_vmstat_pgmajfault", "node_vmstat_pgmajfault{deployment_label, instance_name, monitoring_id}" },
				{ "node_vmstat_pgpgin", "node_vmstat_pgpgin{deployment_label, instance_name, monitoring_id}" },
				{ "node_vmstat_pgpgout", "node_vmstat_pgpgout{deployment_label, instance_name, monitoring_id}" },
				{ "node_vmstat_pswpin", "node_vmstat_pswpin{deployment_label, instance_name, monitoring_id}" },
				{ "node_vmstat_pswpout", "node_vmstat_pswpout{deployment_label, instance_name, monitoring_id}" },
				// Functions
				{ "abs", "abs(v instant-vector) returns the input vector with all sample values converted to their absolute value." },
				{ "absent",
						"absent(v instant-vector) returns an empty vector if the vector passed to it has any elements and a 1-element vector with the value 1 if the vector passed to it has no elements." },
				{ "absent_over_time",
						"absent_over_time(v range-vector) returns an empty vector if the range vector passed to it has any elements and a 1-element vector with the value 1 if the range vector passed to it has no elements." },
				{ "avg_over_time", "the average value of all points in the specified interval" },
				{ "ceil",
						"ceil(v instant-vector) rounds the sample values of all elements in v up to the nearest integer." },
				{ "changes",
						"For each input time series, changes(v range-vector) returns the number of times its value has changed within the provided time range as an instant vector." },
				{ "clamp",
						"clamp(v instant-vector, min scalar, max scalar) clamps the sample values of all elements in v to have a lower limit of min and an upper limit of max." },
				{ "clamp_max",
						"clamp_max(v instant-vector, max scalar) clamps the sample values of all elements in v to have an upper limit of max." },
				{ "clamp_min",
						"clamp_min(v instant-vector, min scalar) clamps the sample values of all elements in v to have a lower limit of min." },
				{ "count_over_time", "the count of all values in the specified interval." },
				{ "day_of_month",
						"day_of_month(v=vector(time()) instant-vector) returns the day of the month for each of the given times in UTC. Returned values are from 1 to 31." },
				{ "day_of_week",
						"day_of_week(v=vecr(time()) instant-vector) returns the day of the week for each of the given times in UTC. Returned values are from 0 to 6, where 0 means Sunday etc." },
				{ "days_in_month",
						"days_in_month(v=vector(time()) instant-vector) returns number of days in the month for each of the given times in UTC. Returned values are from 28 to 31." },
				{ "delta",
						"delta(v range-vector) calculates the difference between the first and last value of each time series element in a range vector v, returning an instant vector with the given deltas and equivalent labels. The delta is extrapolated to cover the full time range as specified in the range vector selector, so that it is possible to get a non-integer result even if the sample values are all integers." },
				{ "deriv",
						"deriv(v range-vector) calculates the per-second derivative of the time series in a range vector v, using simple linear regression." },
				{ "exp", "exp(v instant-vector) calculates the exponential function for all elements in v" },
				{ "floor",
						"floor(v instant-vector) rounds the sample values of all elements in v down to the nearest integer." },
				{ "histogram_quantile",
						"histogram_quantile(φ scalar, b instant-vector) calculates the φ-quantile (0 ≤ φ ≤ 1) from the buckets b of a histogram. (See histograms and summaries for a detailed explanation of φ-quantiles and the usage of the histogram metric type in general.) The samples in b are the counts of observations in each bucket. Each sample must have a label le where the label value denotes the inclusive upper bound of the bucket. (Samples without such a label are silently ignored.) The histogram metric type automatically provides time series with the _bucket suffix and the appropriate labels." },
				{ "holt_winters",
						"holt_winters(v range-vector, sf scalar, tf scalar) produces a smoothed value for time series based on the range in v. The lower the smoothing factor sf, the more importance is given to old data. The higher the trend factor tf, the more trends in the data is considered. Both sf and tf must be between 0 and 1." },
				{ "hour",
						"hour(v=vector(time()) instant-vector) returns the hour of the day for each of the given times in UTC. Returned values are from 0 to 23." },
				{ "idelta",
						"idelta(v range-vector) calculates the difference between the last two samples in the range vector v, returning an instant vector with the given deltas and equivalent labels." },
				{ "increase",
						"increase(v range-vector) calculates the increase in the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. The increase is extrapolated to cover the full time range as specified in the range vector selector, so that it is possible to get a non-integer result even if a counter increases only by integer increments." },
				{ "irate",
						"irate(v range-vector) calculates the per-second instant rate of increase of the time series in the range vector. This is based on the last two data points. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for." },
				{ "label_join",
						"For each timeseries in v, label_join(v instant-vector, dst_label string, separator string, src_label_1 string, src_label_2 string, ...) joins all the values of all the src_labels using separator and returns the timeseries with the label dst_label containing the joined value. There can be any number of src_labels in this function." },
				{ "label_replace",
						"For each timeseries in v, label_replace(v instant-vector, dst_label string, replacement string, src_label string, regex string) matches the regular expression regex against the value of the label src_label. If it matches, the value of the label dst_label in the returned timeseries will be the expansion of replacement, together with the original labels in the input. Capturing groups in the regular expression can be referenced with $1, $2, etc. If the regular expression doesn't match then the timeseries is returned unchanged." },
				{ "last_over_time", "the most recent point value in specified interval." },
				{ "ln", "ln(v instant-vector) calculates the natural logarithm for all elements in v" },
				{ "log2", "log2(v instant-vector) calculates the binary logarithm for all elements in v" },
				{ "log10", "log10(v instant-vector) calculates the decimal logarithm for all elements in v" },
				{ "max_over_time", "the maximum value of all points in the specified interval." },
				{ "minute",
						"minute(v=vector(time()) instant-vector) returns the minute of the hour for each of the given times in UTC. Returned values are from 0 to 59." },
				{ "min_over_time", "the minimum value of all points in the specified interval." },
				{ "month",
						"month(v=vector(time()) instant-vector) returns the month of the year for each of the given times in UTC. Returned values are from 1 to 12, where 1 means January etc." },
				{ "predict_linear",
						"predict_linear(v range-vector, t scalar) predicts the value of time series t seconds from now, based on the range vector v, using simple linear regression." },
				{ "present_over_time", "the value 1 for any series in the specified interval." },
				{ "quantile_over_time", "the φ-quantile (0 ≤ φ ≤ 1) of the values in the specified interval." },
				{ "rate",
						"rate(v range-vector) calculates the per-second average rate of increase of the time series in the range vector. Breaks in monotonicity (such as counter resets due to target restarts) are automatically adjusted for. Also, the calculation extrapolates to the ends of the time range, allowing for missed scrapes or imperfect alignment of scrape cycles with the range's time period." },
				{ "resets",
						"For each input time series, resets(v range-vector) returns the number of counter resets within the provided time range as an instant vector. Any decrease in the value between two consecutive samples is interpreted as a counter reset." },
				{ "round",
						"round(v instant-vector, to_nearest=1 scalar) rounds the sample values of all elements in v to the nearest integer. Ties are resolved by rounding up. The optional to_nearest argument allows specifying the nearest multiple to which the sample values should be rounded. This multiple may also be a fraction." },
				{ "scalar",
						"Given a single-element input vector, scalar(v instant-vector) returns the sample value of that single element as a scalar. If the input vector does not have exactly one element, scalar will result = NaN." },
				{ "sgn", "sgn(v instant-vector) returns a vector with all sample values converted to their sign, defined as this 1 if v is positive, -1 if v is negative and 0 if v is equal to zero." },
				{ "sort",
						"sort(v instant-vector) returns vector elements sorted by their sample values, in ascending order." },
				{ "sort_desc", "Same as sort, but sorts in descending order." },
				{ "sqrt", "sqrt(v instant-vector) calculates the square root of all elements in v." },
				{ "stdvar_over_time", "the population standard variance of the values in the specified interval." },
				{ "stddev_over_time", "the population standard deviation of the values in the specified interval." },
				{ "sum_over_time", "the sum of all values in the specified interval." },
				{ "time",
						"time() returns the number of seconds since January 1, 1970 UTC. Note that this does not actually return the current time, but the time at which the expression is to be evaluated." },
				{ "timestamp",
						"timestamp(v instant-vector) returns the timestamp of each of the samples of the given vector as the number of seconds since January 1, 1970 UTC." },
				{ "vector", "vector(s scalar) returns the scalar s as a vector with no labels." },
				{ "year",
						"year(v=vector(time()) instant-vector) returns the year for each of the given times in UTC." },
				// Aggregation operators
				{ "sum", "calculate sum over dimensions" }, { "min", "select minimum over dimensions" },
				{ "max", "select maximum over dimensions" }, { "avg", "calculate the average over dimensions" },
				{ "group", "all values in the resulting vector are 1" },
				{ "stddev", "calculate population standard deviation over dimensions" },
				{ "stdvar", "calculate population standard variance over dimensions" },
				{ "count", "count number of elements in the vector" },
				{ "count_values", "count number of elements with the same value" },
				{ "bottomk", "smallest k elements by sample value" }, { "topk", "largest k elements by sample value" },
				{ "quantile", "calculate φ-quantile (0 ≤ φ ≤ 1) over dimensions" },
				// Vector matching
				{ "on", "The on keyword allows reducing the set of considered labels to a provided list" },
				{ "ignoring", "The ignoring keyword allows ignoring certain labels when matching" }, })
				.collect(Collectors.toMap(data -> data[0], data -> data[1]));
	}

	public static String getAdditionalProposalInfo(Keyword keyword) {
		String result = "";
		if (keyword instanceof KeywordImpl) {
			KeywordImpl keywordImpl = (KeywordImpl) keyword;
			ParserRule rule = findParserRule(keywordImpl);
			String ruleName = rule.getName();
			String keywordValue = keyword.getValue();

			if (ruleName.equals("EGroup") && keywordValue.equals("group:"))
				result = splitSentence(
						"The name of a group of monitoring alert rules that are evaluated together.Must be unique within a file");
			else if (ruleName.equals("ERule") && keywordValue.equals("alert:"))
				result = splitSentence("The name of the alert rule.");
			else if (ruleName.equals("ERule") && keywordValue.equals("expr:"))
				result = splitSentence(
						"The PromQL expression to evaluate.In every evaluation cycle this expression is evaluated at the current time, and all resultant time series become on pending/firing alerts.");
			else if (ruleName.equals("ERule") && keywordValue.equals("for:"))
				result = splitSentence(
						"Alerts are considered for firing once the expression condition holds for given duration. Alerts which have not yet fired before given duration are considered pending.");
			else if (ruleName.equals("ERule") && keywordValue.equals("labels:"))
				result = splitSentence("Labels to add or overwrite for each alert.");
			else if (ruleName.equals("ERule") && keywordValue.equals("annotations:"))
				result = splitSentence("Annotations to add to each alert.");
		}
		return result;
	}

	public static String getAdditionalProposalInfo(String keyword) {
		return proposals.get(keyword);
	}

	private static ParserRule findParserRule(EObject obj) {
		if (obj == null) {
			return null;
		} else if (obj instanceof ParserRule) {
			return (ParserRule) obj;
		} else {
			return findParserRule(obj.eContainer());
		}
	}

	// Split long sentence into multiple lines
	private static String splitSentence(String string, char delimiter) {
		String str = string;
		int length = str.length();
		int lineLength = 70;
		int index = lineLength;
		while (index < length) {
			index = str.indexOf(delimiter, index);
			if (index > 0 && index < length - 1) {
				str = str.substring(0, index) + "\n" + str.substring(index + 1);
				index += lineLength;
			} else {
				return str;
			}
		}
		return str;
	}

	private static String splitSentence(String string) {
		return splitSentence(string, ' ');
	}
}
