/*
 * generated by Xtext 2.22.0
 */
package org.sodalite.dsl.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.sodalite.dsl.AlertingRuntimeModule;
import org.sodalite.dsl.AlertingStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class AlertingIdeSetup extends AlertingStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new AlertingRuntimeModule(), new AlertingIdeModule()));
	}
	
}
