/**
 * generated by Xtext 2.19.0
 */
package org.sodalite.dsl.optimization.optimization.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.sodalite.dsl.optimization.optimization.EAutotuning;
import org.sodalite.dsl.optimization.optimization.EOptBuild;
import org.sodalite.dsl.optimization.optimization.EOptimization;
import org.sodalite.dsl.optimization.optimization.EOptimizationCases;
import org.sodalite.dsl.optimization.optimization.OptimizationPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>EOptimization</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.impl.EOptimizationImpl#isEnable_opt_build <em>Enable opt build</em>}</li>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.impl.EOptimizationImpl#isEnable_autotuning <em>Enable autotuning</em>}</li>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.impl.EOptimizationImpl#getApp_type <em>App type</em>}</li>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.impl.EOptimizationImpl#getOpt_build <em>Opt build</em>}</li>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.impl.EOptimizationImpl#getAutotuning <em>Autotuning</em>}</li>
 *   <li>{@link org.sodalite.dsl.optimization.optimization.impl.EOptimizationImpl#getApp_optimization <em>App optimization</em>}</li>
 * </ul>
 *
 * @generated
 */
public class EOptimizationImpl extends MinimalEObjectImpl.Container implements EOptimization
{
  /**
   * The default value of the '{@link #isEnable_opt_build() <em>Enable opt build</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnable_opt_build()
   * @generated
   * @ordered
   */
  protected static final boolean ENABLE_OPT_BUILD_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEnable_opt_build() <em>Enable opt build</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnable_opt_build()
   * @generated
   * @ordered
   */
  protected boolean enable_opt_build = ENABLE_OPT_BUILD_EDEFAULT;

  /**
   * The default value of the '{@link #isEnable_autotuning() <em>Enable autotuning</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnable_autotuning()
   * @generated
   * @ordered
   */
  protected static final boolean ENABLE_AUTOTUNING_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isEnable_autotuning() <em>Enable autotuning</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isEnable_autotuning()
   * @generated
   * @ordered
   */
  protected boolean enable_autotuning = ENABLE_AUTOTUNING_EDEFAULT;

  /**
   * The default value of the '{@link #getApp_type() <em>App type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApp_type()
   * @generated
   * @ordered
   */
  protected static final String APP_TYPE_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getApp_type() <em>App type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApp_type()
   * @generated
   * @ordered
   */
  protected String app_type = APP_TYPE_EDEFAULT;

  /**
   * The cached value of the '{@link #getOpt_build() <em>Opt build</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getOpt_build()
   * @generated
   * @ordered
   */
  protected EOptBuild opt_build;

  /**
   * The cached value of the '{@link #getAutotuning() <em>Autotuning</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getAutotuning()
   * @generated
   * @ordered
   */
  protected EAutotuning autotuning;

  /**
   * The cached value of the '{@link #getApp_optimization() <em>App optimization</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getApp_optimization()
   * @generated
   * @ordered
   */
  protected EOptimizationCases app_optimization;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected EOptimizationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return OptimizationPackage.Literals.EOPTIMIZATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEnable_opt_build()
  {
    return enable_opt_build;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnable_opt_build(boolean newEnable_opt_build)
  {
    boolean oldEnable_opt_build = enable_opt_build;
    enable_opt_build = newEnable_opt_build;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__ENABLE_OPT_BUILD, oldEnable_opt_build, enable_opt_build));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isEnable_autotuning()
  {
    return enable_autotuning;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setEnable_autotuning(boolean newEnable_autotuning)
  {
    boolean oldEnable_autotuning = enable_autotuning;
    enable_autotuning = newEnable_autotuning;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__ENABLE_AUTOTUNING, oldEnable_autotuning, enable_autotuning));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getApp_type()
  {
    return app_type;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setApp_type(String newApp_type)
  {
    String oldApp_type = app_type;
    app_type = newApp_type;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__APP_TYPE, oldApp_type, app_type));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EOptBuild getOpt_build()
  {
    return opt_build;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetOpt_build(EOptBuild newOpt_build, NotificationChain msgs)
  {
    EOptBuild oldOpt_build = opt_build;
    opt_build = newOpt_build;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__OPT_BUILD, oldOpt_build, newOpt_build);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setOpt_build(EOptBuild newOpt_build)
  {
    if (newOpt_build != opt_build)
    {
      NotificationChain msgs = null;
      if (opt_build != null)
        msgs = ((InternalEObject)opt_build).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OptimizationPackage.EOPTIMIZATION__OPT_BUILD, null, msgs);
      if (newOpt_build != null)
        msgs = ((InternalEObject)newOpt_build).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OptimizationPackage.EOPTIMIZATION__OPT_BUILD, null, msgs);
      msgs = basicSetOpt_build(newOpt_build, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__OPT_BUILD, newOpt_build, newOpt_build));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EAutotuning getAutotuning()
  {
    return autotuning;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetAutotuning(EAutotuning newAutotuning, NotificationChain msgs)
  {
    EAutotuning oldAutotuning = autotuning;
    autotuning = newAutotuning;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__AUTOTUNING, oldAutotuning, newAutotuning);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setAutotuning(EAutotuning newAutotuning)
  {
    if (newAutotuning != autotuning)
    {
      NotificationChain msgs = null;
      if (autotuning != null)
        msgs = ((InternalEObject)autotuning).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OptimizationPackage.EOPTIMIZATION__AUTOTUNING, null, msgs);
      if (newAutotuning != null)
        msgs = ((InternalEObject)newAutotuning).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OptimizationPackage.EOPTIMIZATION__AUTOTUNING, null, msgs);
      msgs = basicSetAutotuning(newAutotuning, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__AUTOTUNING, newAutotuning, newAutotuning));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EOptimizationCases getApp_optimization()
  {
    return app_optimization;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetApp_optimization(EOptimizationCases newApp_optimization, NotificationChain msgs)
  {
    EOptimizationCases oldApp_optimization = app_optimization;
    app_optimization = newApp_optimization;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION, oldApp_optimization, newApp_optimization);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setApp_optimization(EOptimizationCases newApp_optimization)
  {
    if (newApp_optimization != app_optimization)
    {
      NotificationChain msgs = null;
      if (app_optimization != null)
        msgs = ((InternalEObject)app_optimization).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION, null, msgs);
      if (newApp_optimization != null)
        msgs = ((InternalEObject)newApp_optimization).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION, null, msgs);
      msgs = basicSetApp_optimization(newApp_optimization, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION, newApp_optimization, newApp_optimization));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case OptimizationPackage.EOPTIMIZATION__OPT_BUILD:
        return basicSetOpt_build(null, msgs);
      case OptimizationPackage.EOPTIMIZATION__AUTOTUNING:
        return basicSetAutotuning(null, msgs);
      case OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION:
        return basicSetApp_optimization(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case OptimizationPackage.EOPTIMIZATION__ENABLE_OPT_BUILD:
        return isEnable_opt_build();
      case OptimizationPackage.EOPTIMIZATION__ENABLE_AUTOTUNING:
        return isEnable_autotuning();
      case OptimizationPackage.EOPTIMIZATION__APP_TYPE:
        return getApp_type();
      case OptimizationPackage.EOPTIMIZATION__OPT_BUILD:
        return getOpt_build();
      case OptimizationPackage.EOPTIMIZATION__AUTOTUNING:
        return getAutotuning();
      case OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION:
        return getApp_optimization();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case OptimizationPackage.EOPTIMIZATION__ENABLE_OPT_BUILD:
        setEnable_opt_build((Boolean)newValue);
        return;
      case OptimizationPackage.EOPTIMIZATION__ENABLE_AUTOTUNING:
        setEnable_autotuning((Boolean)newValue);
        return;
      case OptimizationPackage.EOPTIMIZATION__APP_TYPE:
        setApp_type((String)newValue);
        return;
      case OptimizationPackage.EOPTIMIZATION__OPT_BUILD:
        setOpt_build((EOptBuild)newValue);
        return;
      case OptimizationPackage.EOPTIMIZATION__AUTOTUNING:
        setAutotuning((EAutotuning)newValue);
        return;
      case OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION:
        setApp_optimization((EOptimizationCases)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case OptimizationPackage.EOPTIMIZATION__ENABLE_OPT_BUILD:
        setEnable_opt_build(ENABLE_OPT_BUILD_EDEFAULT);
        return;
      case OptimizationPackage.EOPTIMIZATION__ENABLE_AUTOTUNING:
        setEnable_autotuning(ENABLE_AUTOTUNING_EDEFAULT);
        return;
      case OptimizationPackage.EOPTIMIZATION__APP_TYPE:
        setApp_type(APP_TYPE_EDEFAULT);
        return;
      case OptimizationPackage.EOPTIMIZATION__OPT_BUILD:
        setOpt_build((EOptBuild)null);
        return;
      case OptimizationPackage.EOPTIMIZATION__AUTOTUNING:
        setAutotuning((EAutotuning)null);
        return;
      case OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION:
        setApp_optimization((EOptimizationCases)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case OptimizationPackage.EOPTIMIZATION__ENABLE_OPT_BUILD:
        return enable_opt_build != ENABLE_OPT_BUILD_EDEFAULT;
      case OptimizationPackage.EOPTIMIZATION__ENABLE_AUTOTUNING:
        return enable_autotuning != ENABLE_AUTOTUNING_EDEFAULT;
      case OptimizationPackage.EOPTIMIZATION__APP_TYPE:
        return APP_TYPE_EDEFAULT == null ? app_type != null : !APP_TYPE_EDEFAULT.equals(app_type);
      case OptimizationPackage.EOPTIMIZATION__OPT_BUILD:
        return opt_build != null;
      case OptimizationPackage.EOPTIMIZATION__AUTOTUNING:
        return autotuning != null;
      case OptimizationPackage.EOPTIMIZATION__APP_OPTIMIZATION:
        return app_optimization != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (enable_opt_build: ");
    result.append(enable_opt_build);
    result.append(", enable_autotuning: ");
    result.append(enable_autotuning);
    result.append(", app_type: ");
    result.append(app_type);
    result.append(')');
    return result.toString();
  }

} //EOptimizationImpl
