/**
 * generated by Xtext 2.23.0
 */
package org.sodalite.sdl.ansible.ansibleDsl.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.sodalite.sdl.ansible.ansibleDsl.AnsibleDslPackage;
import org.sodalite.sdl.ansible.ansibleDsl.ETaskHandler;
import org.sodalite.sdl.ansible.ansibleDsl.ETaskHandlerAttributes;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ETask Handler</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.sdl.ansible.ansibleDsl.impl.ETaskHandlerImpl#getTask_handler_attributes <em>Task handler attributes</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ETaskHandlerImpl extends EExecutionImpl implements ETaskHandler
{
  /**
   * The cached value of the '{@link #getTask_handler_attributes() <em>Task handler attributes</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTask_handler_attributes()
   * @generated
   * @ordered
   */
  protected ETaskHandlerAttributes task_handler_attributes;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ETaskHandlerImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return AnsibleDslPackage.Literals.ETASK_HANDLER;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ETaskHandlerAttributes getTask_handler_attributes()
  {
    return task_handler_attributes;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTask_handler_attributes(ETaskHandlerAttributes newTask_handler_attributes, NotificationChain msgs)
  {
    ETaskHandlerAttributes oldTask_handler_attributes = task_handler_attributes;
    task_handler_attributes = newTask_handler_attributes;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES, oldTask_handler_attributes, newTask_handler_attributes);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setTask_handler_attributes(ETaskHandlerAttributes newTask_handler_attributes)
  {
    if (newTask_handler_attributes != task_handler_attributes)
    {
      NotificationChain msgs = null;
      if (task_handler_attributes != null)
        msgs = ((InternalEObject)task_handler_attributes).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES, null, msgs);
      if (newTask_handler_attributes != null)
        msgs = ((InternalEObject)newTask_handler_attributes).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES, null, msgs);
      msgs = basicSetTask_handler_attributes(newTask_handler_attributes, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES, newTask_handler_attributes, newTask_handler_attributes));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES:
        return basicSetTask_handler_attributes(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES:
        return getTask_handler_attributes();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES:
        setTask_handler_attributes((ETaskHandlerAttributes)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES:
        setTask_handler_attributes((ETaskHandlerAttributes)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case AnsibleDslPackage.ETASK_HANDLER__TASK_HANDLER_ATTRIBUTES:
        return task_handler_attributes != null;
    }
    return super.eIsSet(featureID);
  }

} //ETaskHandlerImpl
