/**
 * generated by Xtext 2.17.1
 */
package org.sodalite.dsl.rM;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EAssignment Value</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.sodalite.dsl.rM.RMPackage#getEAssignmentValue()
 * @model
 * @generated
 */
public interface EAssignmentValue extends EObject
{
} // EAssignmentValue
