/**
 * generated by Xtext 2.22.0
 */
package org.sodalite.dsl.rM;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EPREFIX TYPE</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.dsl.rM.EPREFIX_TYPE#getModule <em>Module</em>}</li>
 *   <li>{@link org.sodalite.dsl.rM.EPREFIX_TYPE#getType <em>Type</em>}</li>
 * </ul>
 *
 * @see org.sodalite.dsl.rM.RMPackage#getEPREFIX_TYPE()
 * @model
 * @generated
 */
public interface EPREFIX_TYPE extends EDataTypeName
{
  /**
   * Returns the value of the '<em><b>Module</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module</em>' attribute.
   * @see #setModule(String)
   * @see org.sodalite.dsl.rM.RMPackage#getEPREFIX_TYPE_Module()
   * @model
   * @generated
   */
  String getModule();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.EPREFIX_TYPE#getModule <em>Module</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module</em>' attribute.
   * @see #getModule()
   * @generated
   */
  void setModule(String value);

  /**
   * Returns the value of the '<em><b>Type</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Type</em>' attribute.
   * @see #setType(String)
   * @see org.sodalite.dsl.rM.RMPackage#getEPREFIX_TYPE_Type()
   * @model
   * @generated
   */
  String getType();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.EPREFIX_TYPE#getType <em>Type</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Type</em>' attribute.
   * @see #getType()
   * @generated
   */
  void setType(String value);

} // EPREFIX_TYPE
