/**
 * generated by Xtext 2.23.0
 */
package org.sodalite.dsl.rM;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>EPrimary</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.dsl.rM.EPrimary#getFile <em>File</em>}</li>
 *   <li>{@link org.sodalite.dsl.rM.EPrimary#getRelative_path <em>Relative path</em>}</li>
 * </ul>
 *
 * @see org.sodalite.dsl.rM.RMPackage#getEPrimary()
 * @model
 * @generated
 */
public interface EPrimary extends EObject
{
  /**
   * Returns the value of the '<em><b>File</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>File</em>' attribute.
   * @see #setFile(String)
   * @see org.sodalite.dsl.rM.RMPackage#getEPrimary_File()
   * @model
   * @generated
   */
  String getFile();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.EPrimary#getFile <em>File</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>File</em>' attribute.
   * @see #getFile()
   * @generated
   */
  void setFile(String value);

  /**
   * Returns the value of the '<em><b>Relative path</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relative path</em>' attribute.
   * @see #setRelative_path(String)
   * @see org.sodalite.dsl.rM.RMPackage#getEPrimary_Relative_path()
   * @model
   * @generated
   */
  String getRelative_path();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.EPrimary#getRelative_path <em>Relative path</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relative path</em>' attribute.
   * @see #getRelative_path()
   * @generated
   */
  void setRelative_path(String value);

} // EPrimary
