/**
 * generated by Xtext 2.25.0
 */
package org.sodalite.dsl.rM;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ERequirement Definition Body</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getCapability <em>Capability</em>}</li>
 *   <li>{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getNode <em>Node</em>}</li>
 *   <li>{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getRelationship <em>Relationship</em>}</li>
 *   <li>{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getStart <em>Start</em>}</li>
 *   <li>{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getEnd <em>End</em>}</li>
 * </ul>
 *
 * @see org.sodalite.dsl.rM.RMPackage#getERequirementDefinitionBody()
 * @model
 * @generated
 */
public interface ERequirementDefinitionBody extends EObject
{
  /**
   * Returns the value of the '<em><b>Capability</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Capability</em>' containment reference.
   * @see #setCapability(EPREFIX_TYPE)
   * @see org.sodalite.dsl.rM.RMPackage#getERequirementDefinitionBody_Capability()
   * @model containment="true"
   * @generated
   */
  EPREFIX_TYPE getCapability();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getCapability <em>Capability</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Capability</em>' containment reference.
   * @see #getCapability()
   * @generated
   */
  void setCapability(EPREFIX_TYPE value);

  /**
   * Returns the value of the '<em><b>Node</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Node</em>' containment reference.
   * @see #setNode(EPREFIX_TYPE)
   * @see org.sodalite.dsl.rM.RMPackage#getERequirementDefinitionBody_Node()
   * @model containment="true"
   * @generated
   */
  EPREFIX_TYPE getNode();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getNode <em>Node</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Node</em>' containment reference.
   * @see #getNode()
   * @generated
   */
  void setNode(EPREFIX_TYPE value);

  /**
   * Returns the value of the '<em><b>Relationship</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Relationship</em>' containment reference.
   * @see #setRelationship(EPREFIX_TYPE)
   * @see org.sodalite.dsl.rM.RMPackage#getERequirementDefinitionBody_Relationship()
   * @model containment="true"
   * @generated
   */
  EPREFIX_TYPE getRelationship();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getRelationship <em>Relationship</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Relationship</em>' containment reference.
   * @see #getRelationship()
   * @generated
   */
  void setRelationship(EPREFIX_TYPE value);

  /**
   * Returns the value of the '<em><b>Start</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Start</em>' containment reference.
   * @see #setStart(EAlphaNumericValue)
   * @see org.sodalite.dsl.rM.RMPackage#getERequirementDefinitionBody_Start()
   * @model containment="true"
   * @generated
   */
  EAlphaNumericValue getStart();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getStart <em>Start</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Start</em>' containment reference.
   * @see #getStart()
   * @generated
   */
  void setStart(EAlphaNumericValue value);

  /**
   * Returns the value of the '<em><b>End</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>End</em>' containment reference.
   * @see #setEnd(EAlphaNumericValue)
   * @see org.sodalite.dsl.rM.RMPackage#getERequirementDefinitionBody_End()
   * @model containment="true"
   * @generated
   */
  EAlphaNumericValue getEnd();

  /**
   * Sets the value of the '{@link org.sodalite.dsl.rM.ERequirementDefinitionBody#getEnd <em>End</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>End</em>' containment reference.
   * @see #getEnd()
   * @generated
   */
  void setEnd(EAlphaNumericValue value);

} // ERequirementDefinitionBody
