/**
 * generated by Xtext 2.17.1
 */
package org.sodalite.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class RMUiModule extends AbstractRMUiModule {
  public RMUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
